---
all:
  children:
    nextcloud_servers:
      hosts:
        nextcloud-staging:
          ansible_host: "{{ lookup('env', 'STAGING_HOST') | default('192.168.56.102', true) }}"
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('admin', true) }}"
          ansible_become: true
    database_servers:
      hosts:
        nextcloud-staging:
    monitoring_servers:
      hosts:
        nextcloud-staging:
