---
- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  listen: restart fail2ban

- name: restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
  listen: restart auditd
