---
all:
  children:
    nextcloud_servers:
      hosts:
        nextcloud-prod:
          ansible_host: "{{ lookup('env', 'NEXTCLOUD_HOST') | default('192.168.56.101', true) }}"
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('admin', true) }}"
          ansible_become: true
    database_servers:
      hosts:
        nextcloud-prod:
    monitoring_servers:
      hosts:
        nextcloud-prod:
